### ISSUE TITLE
Adding "In Service" flag status on devices

### ISSUE THREAD

**Issue by charlesg** [device42/jamf_to_device42_sync#5]
We started using the script a while ago to update D42 with all the devices managed by Casper JAMF and it really works well for us.

The only issue we ran into is devices that stay at users' home are not reachable by other means (snmp, ping sweep, etc) and end-up listed "Not In Service". 

How could I modify the script to "check" the "In Service" field in Device42 for these devices?

**Comment by cscaglioned42** [comment]
Hi @charlesg 

I think what you would want to do is make an API call to get device info based on the name of the device in starter.py Integration.get_computers.  For example:
https://[D42 Instance]/api/1.0/devices/?name=testdevice

This will return a result like this:
`{
"Devices": [
        {
            "asset_no": "",
            "device_id": 16356,
            "device_url": "/api/1.0/devices/id/16356/",
            "name": "testdevice",
            "serial_no": "",
            "type": "unknown",
            "uuid": ""
        }
    ]
}`

With the device_url from the result of the above API call, you can make another API call to Device42 to get detailed device information including the in_service value.  The API call would look something like:
https://[D42 Instance]/api/1.0/devices/id/16356/

More info about the Device42 API is available at:
https://api.device42.com/

**Comment by charlesg** [comment]
We can make this work.
